#!/usr/bin/env node
/**
 * LifeLog Distribution Agent - Generator
 * 
 * Creates customized integration code, documentation, and PR templates
 * for each candidate project.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Candidate } from './scanner.js';

interface GeneratedIntegration {
  candidate: Candidate;
  integrationCode: string;
  documentation: string;
  prTitle: string;
  prBody: string;
  files: { path: string; content: string }[];
}

function generateIntegrationCode(candidate: Candidate): string {
  const { category, name } = candidate;
  
  // Base integration that all projects get
  let baseCode = `/**
 * LifeLog Integration for ${name}
 * 
 * Add wellness tracking and $LIFE token rewards to your app.
 * Generated by LifeLog Distribution Agent
 * 
 * Installation: npm install @lifelog/sdk
 */

import { LifeLog } from '@lifelog/sdk';

// Initialize LifeLog client
const lifelog = new LifeLog({
  apiKey: process.env.LIFELOG_API_KEY,
  debug: process.env.NODE_ENV === 'development',
});

`;

  // Category-specific integration code
  const categoryCode: Record<Candidate['category'], string> = {
    productivity: `// === Productivity Tracking ===

/**
 * Log when a task is completed
 */
export async function onTaskComplete(task: { id: string; title: string; duration?: number }) {
  await lifelog.checkIn({
    message: \`Completed task: \${task.title}\`,
    category: 'productivity',
    duration: task.duration || 30,
    metadata: { taskId: task.id },
  });
}

/**
 * Track daily productivity goal
 */
export async function updateProductivityGoal(minutesWorked: number, targetMinutes: number = 240) {
  const result = await lifelog.trackGoal({
    name: 'Daily Focus Time',
    progress: minutesWorked,
    total: targetMinutes,
    unit: 'minutes',
    category: 'productivity',
  });
  
  if (result.completed) {
    console.log(\`🎉 Goal complete! Earned \${result.reward} $LIFE\`);
  }
  
  return result;
}

/**
 * Log a Pomodoro/focus session
 */
export async function logFocusSession(sessionMinutes: number, taskDescription?: string) {
  await lifelog.logActivity({
    type: 'end_session',
    name: 'focus_session',
    duration: sessionMinutes,
    metadata: { task: taskDescription },
  });
}

/**
 * Log a break (wellness reminder)
 */
export async function logBreak(breakMinutes: number) {
  await lifelog.checkIn({
    message: 'Taking a healthy break',
    category: 'wellness',
    duration: breakMinutes,
  });
}
`,
    gaming: `// === Gaming Achievement Tracking ===

/**
 * Log an in-game achievement
 */
export async function onAchievementUnlocked(achievement: { 
  name: string; 
  points?: number; 
  rarity?: 'common' | 'rare' | 'epic' | 'legendary';
}) {
  const pointsMap = { common: 25, rare: 50, epic: 100, legendary: 250 };
  const points = achievement.points || pointsMap[achievement.rarity || 'common'];
  
  await lifelog.logActivity({
    type: 'achievement',
    name: achievement.name,
    points,
    metadata: { rarity: achievement.rarity },
  });
  
  console.log(\`🏆 Achievement logged! Earned \${points} $LIFE\`);
}

/**
 * Log a gaming session
 */
export async function logGamingSession(sessionMinutes: number, gameName?: string) {
  await lifelog.checkIn({
    message: \`Gaming session: \${gameName || 'game'}\`,
    category: 'gaming',
    duration: sessionMinutes,
  });
  
  // Wellness nudge for long sessions
  if (sessionMinutes > 120) {
    console.log('💡 Pro tip: Consider a short break for your eyes and body!');
  }
}

/**
 * Track in-game milestone
 */
export async function onMilestoneReached(milestone: { name: string; level?: number }) {
  await lifelog.logActivity({
    type: 'milestone',
    name: milestone.name,
    metadata: { level: milestone.level },
  });
}

/**
 * Track healthy gaming goal
 */
export async function updateGamingGoal(sessionsThisWeek: number, targetSessions: number = 5) {
  return await lifelog.trackGoal({
    name: 'Weekly Gaming Sessions',
    progress: sessionsThisWeek,
    total: targetSessions,
    category: 'gaming',
  });
}
`,
    defi: `// === Trading Journal & Decision Tracking ===

/**
 * Log a trade for journaling
 */
export async function logTrade(trade: {
  action: 'buy' | 'sell' | 'swap';
  asset: string;
  amount: number;
  price?: number;
  reasoning?: string;
}) {
  await lifelog.checkIn({
    message: \`Trade: \${trade.action} \${trade.amount} \${trade.asset}\`,
    category: 'trading',
    metadata: {
      action: trade.action,
      asset: trade.asset,
      amount: trade.amount,
      price: trade.price,
      reasoning: trade.reasoning,
    },
  });
}

/**
 * Track strategy adherence goal
 */
export async function updateStrategyGoal(rulesFollowed: number, totalRules: number = 5) {
  return await lifelog.trackGoal({
    name: 'Trading Rules Adherence',
    progress: rulesFollowed,
    total: totalRules,
    category: 'trading',
  });
}

/**
 * Log research session
 */
export async function logResearchSession(topic: string, durationMinutes: number) {
  await lifelog.checkIn({
    message: \`Research: \${topic}\`,
    category: 'research',
    duration: durationMinutes,
  });
}

/**
 * Daily trading journal entry
 */
export async function addJournalEntry(entry: { 
  reflection: string; 
  lessonsLearned?: string;
  tomorrowPlan?: string;
}) {
  await lifelog.checkIn({
    message: 'Daily trading journal entry',
    category: 'journaling',
    metadata: entry,
  });
}

/**
 * Track profitable trades goal
 */
export async function updateProfitGoal(profitableTrades: number, totalTrades: number) {
  const winRate = Math.round((profitableTrades / totalTrades) * 100);
  return await lifelog.trackGoal({
    name: 'Win Rate Goal',
    progress: winRate,
    total: 60, // 60% win rate target
    unit: 'percent',
  });
}
`,
    social: `// === Social Wellness Tracking ===

/**
 * Log a wellness check-in
 */
export async function dailyCheckIn(mood: 1 | 2 | 3 | 4 | 5, note?: string) {
  await lifelog.checkIn({
    message: note || 'Daily check-in',
    category: 'social',
    mood,
  });
}

/**
 * Log social interaction
 */
export async function logSocialActivity(activity: { 
  type: 'chat' | 'call' | 'meetup' | 'collaboration';
  duration?: number;
  description?: string;
}) {
  await lifelog.checkIn({
    message: activity.description || \`Social activity: \${activity.type}\`,
    category: 'social',
    duration: activity.duration,
    metadata: { type: activity.type },
  });
}

/**
 * Track group goal progress
 */
export async function updateGroupGoal(goalName: string, progress: number, total: number) {
  return await lifelog.trackGoal({
    name: goalName,
    progress,
    total,
    category: 'group',
  });
}

/**
 * Log content creation
 */
export async function logContentCreation(content: {
  type: 'post' | 'article' | 'video' | 'podcast';
  title: string;
  durationMinutes?: number;
}) {
  await lifelog.checkIn({
    message: \`Created: \${content.title}\`,
    category: 'content',
    duration: content.durationMinutes,
    metadata: { type: content.type },
  });
  
  await lifelog.logActivity({
    type: 'achievement',
    name: \`Published \${content.type}\`,
    points: 75,
  });
}
`,
    developer: `// === Developer Productivity Tracking ===

/**
 * Log coding session
 */
export async function logCodingSession(session: {
  duration: number;
  language?: string;
  project?: string;
  description?: string;
}) {
  await lifelog.checkIn({
    message: session.description || \`Coding: \${session.project || 'project'}\`,
    category: 'coding',
    duration: session.duration,
    metadata: {
      language: session.language,
      project: session.project,
    },
  });
}

/**
 * Track daily coding goal
 */
export async function updateCodingGoal(minutesCoded: number, targetMinutes: number = 240) {
  return await lifelog.trackGoal({
    name: 'Daily Coding Time',
    progress: minutesCoded,
    total: targetMinutes,
    unit: 'minutes',
    category: 'coding',
  });
}

/**
 * Log commit/PR for achievement tracking
 */
export async function logCommit(commit: { message: string; repo?: string; isPR?: boolean }) {
  await lifelog.logActivity({
    type: 'achievement',
    name: commit.isPR ? 'PR Merged' : 'Commit Pushed',
    points: commit.isPR ? 100 : 25,
    metadata: { repo: commit.repo, message: commit.message },
  });
}

/**
 * Track break reminders (prevent burnout)
 */
export async function logBreak(minutes: number) {
  await lifelog.checkIn({
    message: 'Developer break - stretching & rest',
    category: 'wellness',
    duration: minutes,
  });
}

/**
 * Track learning/reading
 */
export async function logLearning(topic: string, minutes: number) {
  await lifelog.checkIn({
    message: \`Learning: \${topic}\`,
    category: 'learning',
    duration: minutes,
  });
}

/**
 * Track weekly commits goal
 */
export async function updateCommitsGoal(commits: number, target: number = 20) {
  return await lifelog.trackGoal({
    name: 'Weekly Commits',
    progress: commits,
    total: target,
  });
}
`,
    other: `// === General Activity Tracking ===

/**
 * Log any activity
 */
export async function logActivity(description: string, category?: string, duration?: number) {
  await lifelog.checkIn({
    message: description,
    category: category || 'general',
    duration,
  });
}

/**
 * Track custom goal
 */
export async function trackCustomGoal(name: string, progress: number, total: number) {
  return await lifelog.trackGoal({
    name,
    progress,
    total,
  });
}

/**
 * Log achievement
 */
export async function unlockAchievement(name: string, points?: number) {
  await lifelog.logActivity({
    type: 'achievement',
    name,
    points: points || 50,
  });
}

/**
 * Daily mood check-in
 */
export async function moodCheckIn(mood: 1 | 2 | 3 | 4 | 5, energy?: 1 | 2 | 3 | 4 | 5) {
  await lifelog.checkIn({
    message: 'Daily wellness check',
    category: 'wellness',
    mood,
    energy,
  });
}
`,
  };

  // Footer with exports and utilities
  const footer = `

// === Utility Functions ===

/**
 * Get current streaks
 */
export async function getStreaks() {
  return await lifelog.getStreaks();
}

/**
 * Get $LIFE token balance
 */
export async function getTokenBalance(walletAddress?: string) {
  return await lifelog.getTokenBalance(walletAddress);
}

/**
 * Get daily insight
 */
export async function getDailyInsight(date?: string) {
  return await lifelog.getDailyInsight(date);
}

/**
 * Export local data
 */
export function exportData() {
  return lifelog.exportLocalData();
}

// Export the client for advanced usage
export { lifelog };
`;

  return baseCode + categoryCode[category] + footer;
}

function generateDocumentation(candidate: Candidate): string {
  const { name, category, valueProposition, integrationIdea } = candidate;
  
  return `# LifeLog Integration for ${name}

${valueProposition}

## Quick Start

### 1. Install the SDK

\`\`\`bash
npm install @lifelog/sdk
# or
yarn add @lifelog/sdk
\`\`\`

### 2. Set up your API key (optional)

\`\`\`bash
# .env
LIFELOG_API_KEY=your_api_key  # Optional - works in local-only mode too
\`\`\`

### 3. Import and use

\`\`\`typescript
import { onTaskComplete, updateProductivityGoal } from './lifelog-integration';

// Log when a user completes something
await onTaskComplete({ id: 'task-1', title: 'Deployed smart contract' });

// Track goal progress
await updateProductivityGoal(180, 240); // 3 hours of 4 hour goal
\`\`\`

## Integration Ideas for ${name}

${integrationIdea}

### Suggested Integration Points

${category === 'productivity' ? `
- **Task completion**: Call \`onTaskComplete()\` when users finish tasks
- **Focus sessions**: Use \`logFocusSession()\` for Pomodoro/deep work
- **Daily goals**: Track with \`updateProductivityGoal()\`
- **Break reminders**: Log healthy breaks with \`logBreak()\`
` : ''}
${category === 'gaming' ? `
- **Achievements**: Call \`onAchievementUnlocked()\` for in-game achievements
- **Sessions**: Track play time with \`logGamingSession()\`
- **Milestones**: Log level-ups and milestones
- **Healthy gaming**: Encourage breaks after long sessions
` : ''}
${category === 'defi' ? `
- **Trade logging**: Use \`logTrade()\` for journaling entries
- **Strategy tracking**: Track rule adherence with \`updateStrategyGoal()\`
- **Research**: Log learning sessions with \`logResearchSession()\`
- **Daily journal**: Add reflections with \`addJournalEntry()\`
` : ''}
${category === 'social' ? `
- **Daily check-ins**: Use \`dailyCheckIn()\` for wellness tracking
- **Social activities**: Log interactions with \`logSocialActivity()\`
- **Group goals**: Track community goals with \`updateGroupGoal()\`
- **Content creation**: Celebrate creations with \`logContentCreation()\`
` : ''}
${category === 'developer' ? `
- **Coding sessions**: Track with \`logCodingSession()\`
- **Daily goals**: Use \`updateCodingGoal()\` for targets
- **Commits/PRs**: Log achievements with \`logCommit()\`
- **Learning**: Track growth with \`logLearning()\`
` : ''}
${category === 'other' ? `
- **Activity logging**: Use \`logActivity()\` for any event
- **Custom goals**: Track with \`trackCustomGoal()\`
- **Achievements**: Celebrate with \`unlockAchievement()\`
- **Mood tracking**: Daily wellness with \`moodCheckIn()\`
` : ''}

## $LIFE Token Rewards

Users earn $LIFE tokens for completing wellness activities:

| Action | Reward |
|--------|--------|
| Complete daily goal | 100 $LIFE |
| Complete weekly goal | 500 $LIFE |
| Achievement unlocked | 50+ $LIFE |
| Milestone reached | 200 $LIFE |
| Streak bonus | 50 $LIFE/day |

## Features

- 📊 **Local-first**: All data stored locally by default
- 🔐 **Privacy-focused**: No cloud sync unless you want it
- 💰 **$LIFE rewards**: Earn tokens for healthy habits
- 🤖 **AI insights**: Get personalized coaching (coming soon)
- 📱 **Cross-platform**: Works in Node.js, browsers, and React Native

## API Reference

See the full [@lifelog/sdk documentation](https://github.com/0xrichyrich/lifelog-agent/tree/main/sdk#readme).

## Questions?

- GitHub: [0xrichyrich/lifelog-agent](https://github.com/0xrichyrich/lifelog-agent)
- Issues: [Report a bug](https://github.com/0xrichyrich/lifelog-agent/issues)

---

Built with ❤️ by the LifeLog team for the hackathon community.
`;
}

function generatePRTemplate(candidate: Candidate): { title: string; body: string } {
  const { name, category, valueProposition, repo } = candidate;
  
  const categoryEmoji: Record<Candidate['category'], string> = {
    productivity: '📊',
    gaming: '🎮',
    defi: '📈',
    social: '🤝',
    developer: '💻',
    other: '🧠',
  };

  const title = `${categoryEmoji[category]} Add LifeLog wellness integration`;
  
  const body = `## ${categoryEmoji[category]} Add LifeLog Wellness Integration

Hey! I noticed ${name} could benefit from wellness tracking, so I built a drop-in integration.

### Why This Helps Your Users

${valueProposition}

### What's Included

- **\`lifelog-integration.ts\`** — Drop-in SDK wrapper with category-specific functions
- **\`LIFELOG_INTEGRATION.md\`** — Full documentation and examples
- Ready to use with TypeScript/JavaScript

### Quick Example

\`\`\`typescript
import { ${category === 'productivity' ? 'onTaskComplete, updateProductivityGoal' : 
  category === 'gaming' ? 'onAchievementUnlocked, logGamingSession' :
  category === 'defi' ? 'logTrade, updateStrategyGoal' :
  category === 'social' ? 'dailyCheckIn, logSocialActivity' :
  category === 'developer' ? 'logCodingSession, updateCodingGoal' :
  'logActivity, trackCustomGoal'} } from './lifelog-integration';

// Example usage in your app
${category === 'productivity' ? `await onTaskComplete({ id: '1', title: 'Completed task' });
await updateProductivityGoal(180, 240); // 3/4 hours` :
  category === 'gaming' ? `await onAchievementUnlocked({ name: 'First Win', rarity: 'rare' });
await logGamingSession(45, 'your-game');` :
  category === 'defi' ? `await logTrade({ action: 'buy', asset: 'SOL', amount: 10 });
await updateStrategyGoal(4, 5); // 4/5 rules followed` :
  category === 'social' ? `await dailyCheckIn(4, 'Feeling great today!');
await logSocialActivity({ type: 'meetup', duration: 60 });` :
  category === 'developer' ? `await logCodingSession({ duration: 90, language: 'TypeScript' });
await updateCodingGoal(180, 240);` :
  `await logActivity('Completed onboarding', 'milestone', 15);
await trackCustomGoal('Daily goal', 1, 1);`}
\`\`\`

### Installation

\`\`\`bash
npm install @lifelog/sdk
\`\`\`

### User Benefits

- 📊 Track ${category === 'productivity' ? 'productivity patterns' :
  category === 'gaming' ? 'gaming achievements' :
  category === 'defi' ? 'trading decisions' :
  category === 'social' ? 'wellness and connections' :
  category === 'developer' ? 'coding sessions' :
  'activities'} automatically
- 💰 Earn $LIFE tokens for hitting goals
- 🔥 Build streaks and habits
- 🧠 Get AI-powered insights (coming soon)

### About LifeLog

LifeLog is a multimodal AI life coach with on-chain rewards. This integration was built for the hackathon to help projects add value through wellness tracking.

**No pressure to merge!** Just thought this might be useful. Happy to iterate if you have feedback or want changes.

---

🤖 Generated by [LifeLog Distribution Agent](https://github.com/0xrichyrich/lifelog-agent) | Built with care, not spam
`;

  return { title, body };
}

function generateIntegration(candidate: Candidate): GeneratedIntegration {
  const integrationCode = generateIntegrationCode(candidate);
  const documentation = generateDocumentation(candidate);
  const { title: prTitle, body: prBody } = generatePRTemplate(candidate);

  return {
    candidate,
    integrationCode,
    documentation,
    prTitle,
    prBody,
    files: [
      { path: 'lifelog-integration.ts', content: integrationCode },
      { path: 'LIFELOG_INTEGRATION.md', content: documentation },
    ],
  };
}

function generateAllIntegrations(candidatesPath: string): GeneratedIntegration[] {
  const candidatesFile = fs.readFileSync(candidatesPath, 'utf-8');
  const { candidates } = JSON.parse(candidatesFile);
  
  console.log(`📝 Generating integrations for ${candidates.length} candidates...\n`);
  
  const integrations: GeneratedIntegration[] = [];
  
  for (const candidate of candidates) {
    if (candidate.fitScore >= 5) { // Only generate for good fits
      const integration = generateIntegration(candidate);
      integrations.push(integration);
      console.log(`✅ Generated for ${candidate.repo} (score: ${candidate.fitScore})`);
    }
  }

  // Save generated integrations
  const outputPath = path.join(path.dirname(candidatesPath), 'integrations.json');
  fs.writeFileSync(outputPath, JSON.stringify(integrations, null, 2));
  console.log(`\n📦 Saved ${integrations.length} integrations to integrations.json`);

  return integrations;
}

// Run if executed directly
if (process.argv[1]?.includes('generator')) {
  const candidatesPath = new URL('./candidates.json', import.meta.url).pathname;
  if (fs.existsSync(candidatesPath)) {
    generateAllIntegrations(candidatesPath);
  } else {
    console.error('❌ No candidates.json found. Run scanner first.');
  }
}

export { generateIntegration, generateAllIntegrations, GeneratedIntegration };
